import i18next from "i18next";
import { initReactI18next } from "react-i18next";

export const internalization = i18next.use(initReactI18next).init({
	lng: "en",
	resources: {
		en: {
			translation: {
				inventories: "Inventories",
				settings: "Settings",
				users: "Users",
				login: "Login",
				signUp: "Sign up",
				needAccount: "Need to create an account?",
				haveAccount: "Already have an account?",
				email: "Email",
				enterEmail: "Enter your email",
				password: "Password",
				enterPassword: "Enter your password",
				name: "Name",
				enterName: "Enter your name",
				enterWithFacebook: "Enter with Facebook",
				enterWithGoogle: "Enter with Google",
				createInventory: "Create inventory",
				title: "Title",
				description: "Description",
				string: "String",
				text: "Text",
				integer: "Integer",
				link: "Link",
				boolean: "Boolean",
				submit: "Submit",
				add: "Add",
				fixed: "Fixed",
				twentyBitRandom: "20-bit random number",
				thirtyTwoBitRandom: "32-bit random number",
				sixDigitRandom: "6-digit random number",
				nineDigitRandom: "9-digit random number",
				guid: "GUID",
				sequence: "Sequence",
				date: "Date",
				items: "Items",
				chat: "Chat",
				customId: "Custom ID",
				fields: "Fields",
				access: "Access",
				stats: "Stats",
				loading: "Loading...",
				noRowsToDisplay: "No rows to display.",
				addItem: "Add item",
				yes: "Yes",
				no: "No",
				language: "Language",
				english: "English",
				russian: "Russian",
				actions: "Actions",
				role: "Role",
			},
		},
		ru: {
			translation: {
				inventories: "Инвентари",
				settings: "Настройки",
				users: "Пользователи",
				login: "Логин",
				signUp: "Регистрация",
				needAccount: "Нужно создать аккаунт?",
				haveAccount: "Уже есть аккаунт?",
				email: "Электронная почта",
				enterEmail: "Введите вашу электронную почту",
				password: "Пароль",
				enterPassword: "Введите ваш пароль",
				name: "Имя",
				enterName: "Введите ваше имя",
				enterWithFacebook: "Войти с Facebook",
				enterWithGoogle: "Войти с Google",
				createInventory: "Создать инвентарь",
				title: "Заголовок",
				description: "Описание",
				string: "Строка",
				text: "Текст",
				integer: "Целое число",
				link: "Ссылка",
				boolean: "Булево значение",
				submit: "Отправить",
				add: "Добавить",
				fixed: "Фиксированная",
				twentyBitRandom: "20-бит случайное число",
				thirtyTwoBitRandom: "32-бит случайное число",
				sixDigitRandom: "6-цифровое случайное число",
				nineDigitRandom: "9-цифровое случайное число",
				guid: "GUID",
				sequence: "Последовательность",
				date: "Дата",
				items: "Элементы",
				chat: "Чат",
				customId: "Пользовательский ID",
				fields: "Поля",
				access: "Доступ",
				stats: "Статистика",
				loading: "Загрузка...",
				noRowsToDisplay: "Нет строк для отображения.",
				addItem: "Добавить элемент",
				yes: "Да",
				no: "Нет",
				language: "Язык",
				english: "English",
				russian: "Русский",
				actions: "Действия",
				role: "Роль",
				cancel: "Отмена",
			},
		},
	},
});
